package-lock.json
src/api/organization.ts
src/components/InputCopy/index.tsx
src/components/organization/DedicatedIllustrate.tsx
src/components/organization/OrgDropDown.tsx
src/components/organization/OrganizationDetails.tsx
src/components/organization/SharedIllustrate.tsx
src/components/organization/WalletSpinup.tsx
src/config/apiRoutes.ts

- Worked on the issue of radio selection after agent spinup.
- Added agent spinup illustrations for shared & dedicated.
- Solved issue when we click on copy seed agent spinup started if form filled

fixed: radio selection after agent spinup: 257

---

src/components/organization/EditOrgdetailsModal.tsx

fix: Edit Organization logo bug

---

src/api/issuance.ts
src/components/Issuance/CredDefSelection.tsx
src/config/apiRoutes.ts
src/pages/organizations/issued-credentials/schemas/cred-defs/index.astro

Implemented Credential Definitions selection functionality in issuance flow.

Implemented Credential Definitions selection functionality in issuance flow

---

.github/workflows/deploy.yml
astro.config.mjs
src/api/Auth.ts
src/app/LayoutCommon.astro
src/config/SocketConfig.ts
src/config/envConfig.ts
src/env.d.ts
src/pages/authentication/sign-up.astro
src/pages/index.astro
src/pages/server.ts
src/services/axiosIntercepter.ts

- Worked on the `Deno.env` working changes for deno deploy

Worked on the deno env deploy changes

---

src/api/Auth.ts
src/api/issuance.ts
src/components/Issuance/ConnectionList.tsx
src/components/Issuance/Connections.tsx
src/components/Issuance/CredDefSelection.tsx
src/components/Issuance/EmailList.tsx
src/components/Issuance/Issuance.tsx
src/components/Issuance/IssuedCrdentials.tsx
src/components/Issuance/SchemaSelection.tsx
src/config/CommonConstant.ts
src/config/apiRoutes.ts
src/config/pathRoutes.ts
src/pages/organizations/issued-credentials/index.astro
src/pages/organizations/issued-credentials/schemas/cred-defs/connections/issuance.astro

Implemented issue credential functionality.
https://github.com/credebl/studio/assets/107561764/f99cab9e-3ae0-40b0-b04b-1f3c9c3d03d2

Implemented issue credential functionality

---

src/components/Resources/Schema/ViewSchema.tsx

- Handled missing schema details for view schema page

fix:handled undefined schema details

---

src/api/organization.ts
src/components/organization/OrganizationDetails.tsx
src/components/organization/invitations/SendInvitationModal.tsx
src/components/organization/users/EditUserRolesModal.tsx
src/components/organization/users/Members.tsx

- Worked on the default select member role on update members modal.
- Worked on the search users issue.

fix: user search on users list, disable member role: 89-92

---

src/api/issuance.ts
src/commonComponents/SchemaCard.tsx
src/commonComponents/datatable/index.tsx
src/components/Issuance/CredDefSelection.tsx
src/components/Issuance/Issuance.tsx

fix:Issuance flow

---

src/api/verification.ts
src/app/SideBar.astro
src/common/enums.ts
src/commonComponents/ProofRequestPopup.tsx
src/commonComponents/SchemaCard.tsx
src/commonComponents/datatable/index.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/Resources/Schema/ViewSchema.tsx
src/components/Verification/ConnectionList.tsx
src/components/Verification/Connections.tsx
src/components/Verification/CredDefSelection.tsx
src/components/Verification/EmailList.tsx
src/components/Verification/SchemaSelection.tsx
src/components/Verification/Verification.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/Verification/interface.ts
src/config/CommonConstant.ts
src/config/apiRoutes.ts
src/config/pathRoutes.ts
src/pages/organizations/verification/index.astro
src/pages/organizations/verification/schemas/cred-defs/connections/index.astro
src/pages/organizations/verification/schemas/cred-defs/connections/verification.astro
src/pages/organizations/verification/schemas/cred-defs/index.astro
src/pages/organizations/verification/schemas/index.astro

- User can select the schema for the list(Page)
- User can select the credential-definition restriction(Page)
- User can select the connection for the connection list(Page)
- User can select the attributes for request-verification(Page)

feat: Implemented credential verification flow

---

src/commonComponents/SchemaCard.tsx
src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/Resources/Schema/ViewSchema.tsx

-  Removed the Alert message for schema list page
- Included the Back button on schema and cred-def page
- Included Information tooltip for Schema and cred-def page
-  Replace "Check on Ledger with Hyperlink to the button

fix: remove alert message

---

src/components/Resources/Schema/Create.tsx
src/components/Verification/VerificationCredentialList.tsx

Verification List page
- Added Icon for "Request" button.
Create Schema Page
- Changed "Back" button color Black to Primary 700
- Changed "Reset" Button Icon and changed  color Black to Primary 700
- Aligned "Back" button.

64 change color icon alignment

---

src/components/organization/OrganizationDetails.tsx

- Worked on the org dashboard page break issue due to `null` data of the ledgers

Org dashboard page break issue

---

src/components/Resources/Schema/Create.tsx

fixed:data-type-select

---

src/api/Schema.ts
src/components/Resources/Schema/SchemasList.tsx
src/config/apiRoutes.ts

- Integrated get all schemas from platform

feat: added get all schema list from platform on list schema page

---

src/components/Issuance/Issuance.tsx
src/components/Resources/Schema/Create.tsx
src/components/Verification/Verification.tsx

Fixed: issuance verfication changes as per new schema attributes data types

issuance-verfication-changes-asper-newschema

---

src/api/Agent.ts
src/app/NavBarSidebar.astro
src/commonComponents/AgentHealth.tsx
src/config/apiRoutes.ts

- Implemented agent health indicator

feat: agent health notification

---

src/commonComponents/AgentHealth.tsx

- Added delay in agent health method

fix added delay in agent health API

---

src/app/NavBarSidebar.astro
src/components/Issuance/ConnectionList.tsx
src/components/Verification/ConnectionList.tsx
src/components/Verification/Connections.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/organization/WalletSpinup.tsx

- Added `created on` on connection list
- Fixed reload issue for verification
- Disabled `dedicated` agent spinup button

feat: added created date in connection list

---

src/components/Authentication/SignUpUserName.tsx

- Resolved the continue button click issue on sign up page.

worked on the continue button issue on sign up

---

src/app/SideBar.astro
src/commonComponents/QRcode.tsx

Dashboard and sidebar

---

src/app/SideBar.astro

fix: Dashboard and sidebar

---

src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/interfaces/index.ts

WHAT:
- In this pull request, I've made changes to the to fix alignment issue of schema attribute.
-  Delete button colour changes.
WHY: 
- The reason for these changes is when user add an attribute alignment of add and delete button changes.
- Danger colour is applied to delete button.

fix:schema-attribute-alignment

---

src/commonComponents/AgentHealth.tsx

- Handled agent health for the empty organization

fix: handled agent health for empty organization

---

src/app/LayoutCommon.astro
src/components/Authentication/SignInUserPassword.tsx
src/supabase.ts

- Displayed the loading spinner on the forgot password feature
- Worked on the .env variable access on the client side.

Worked on the forgot password spinner function

---

src/components/Authentication/ResetPassword.tsx

- Fixed the double click on reset password submit redirecting to next page.

fix: double click issue on submit button

---

src/config/envConfig.ts

- Set the env variables to work locally

env variables setup for local

---

src/commonComponents/CredentialDefinitionCard.tsx
src/commonComponents/SchemaCard.tsx
src/components/Issuance/Issuance.tsx
src/components/Resources/Schema/Schemas.tsx
src/components/Resources/Schema/ViewSchema.tsx

- Implemented issuance flow from credential-definition page
- Stored the schema details on schemas page

feat: Implemented issuance flow from credential-definition page

---

src/components/Verification/VerificationCredentialList.tsx

WHAT
- verification list connection id column replaced by request id

fix: verificationlist column name preferance changes

---

README.md

docs: Mention Licence

---

src/app/NavBarSidebar.astro
src/components/Profile/DisplayProfileImg.tsx

- Worked on the user profile image display and details display.

fix: worked on the user profile image and dropdown display

---

src/components/InputCopy/index.tsx
src/components/organization/Dashboard.tsx
src/components/organization/SharedIllustrate.tsx
src/components/organization/WalletSpinup.tsx

- Worked on the wallet spinup seed design and copy button
- Worked on the wallet spinup steps.

fix: worked on the wallet seed design and shared illustrations

---

src/components/Issuance/IssuedCrdentials.tsx

- fixed issue for issue-credential list

fix: credentials Datatable

---

src/commonComponents/ProofRequestPopup.tsx
src/components/Verification/VerificationCredentialList.tsx

- Fixed the verification attributes popup

Worked on the verification popup atributes

---

src/components/Issuance/IssuedCrdentials.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/organization/Dashboard.tsx
src/components/organization/OrganizationDetails.tsx
src/config/pathRoutes.ts

- Removed Pagination from Issuance and Verification
- Changed 'agent spined successfully' to 'Wallet created successfully' 
- Changed 'Wallet Type' to 'Agent Type'

fix: pagination-and-wallet-spinup-minor-changes

---

src/app/SideBar.astro
src/components/Authentication/SignInUserPasskey.tsx
src/components/Profile/AddPasskey.tsx

- Resolved success message bug on sign in page.

Resolved Success Message Display bug on Sign in page

---

src/commonComponents/ProofRequestPopup.tsx

- Changes in verification popup as per figma design

fix: verification popup as per figma

---

src/components/Authentication/SignInUser.tsx
src/components/Authentication/SignUpUserPasskey.tsx
src/components/Authentication/SignUpUserPassword.tsx

- Worked on email address in populating in sign in textbox after the sign up process.

Worked on pre-populate email after sign up user process

---

src/commonComponents/DeviceDetailsCard.tsx
src/components/Profile/AddPasskey.tsx
src/components/User/UserDashBoard.tsx
src/components/organization/OrganizationDetails.tsx
src/components/organization/invitations/Invitations.tsx
src/components/organization/invitations/ReceivedInvitations.tsx
src/utils/DateConversion.ts

- Data Format is consistent throughout the application

fix: fixed date format consistency in the entire application

---

src/common/enums.ts
src/components/Issuance/IssuedCrdentials.tsx
src/components/Verification/ProofRequestPopup.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/organization/WalletSpinup.tsx
src/pages/index.astro

- Issuance and verification status messages replaced.
- Color code added as per status.
- Added SVG to create wallet button.
- Initial status messages are more technical to understand for user.

239 fix technical text replacement

---

src/api/Auth.ts
src/commonComponents/DeviceDetailsCard.tsx
src/commonComponents/PasseyAddDevicePopup.tsx
src/components/Authentication/SignInUserPasskey.tsx
src/components/Profile/AddPasskey.tsx
src/config/apiRoutes.ts

- Disabled revoke button for passkey
- Implemented passkey loader for login page

feat: disabled revoke button for passkey

---

package-lock.json
src/commonComponents/DeviceDetailsCard.tsx
src/components/Tooltip/index.tsx

- Fixed data type in Date Tooltip component

fix: date-tooltip

---

src/components/Authentication/SignInUserPasskey.tsx
src/pages/privacy-policy.md
src/pages/terms-and-conditions.md
src/styles/markdown.css

- Added content for terms conditions and privacy policy page

Terms conditions and privacy policies

---

src/components/organization/Dashboard.tsx
src/components/organization/interfaces/index.ts

- Added feature of Public view in organizations

feat: public view

---

src/components/Resources/Schema/ViewSchema.tsx

- View Schema responsiveness fixed

fix: view schema responsiveness

---

src/components/Authentication/SignInUserPasskey.tsx
src/components/Profile/AddPasskey.tsx

- fixed passkey add-device loader issue

fix: passkey add device loader issue

---

src/components/Profile/AddPasskey.tsx

- Commented get user device details

fix: add device alert message issue

---

src/components/Profile/EditUserProfile.tsx
src/components/Profile/interfaces/index.ts
src/components/organization/EditOrgdetailsModal.tsx
src/components/organization/interfaces/index.ts

- Implemented public/ private selection functionality in edit organization.

refactor: edit organization for private/public option

---

src/components/Profile/DisplayUserProfile.tsx
src/components/Profile/EditUserProfile.tsx
src/components/Profile/interfaces/index.ts
src/components/organization/EditOrgdetailsModal.tsx
src/components/organization/interfaces/index.ts

- Implemented private public selection process in the edit user

refactor: changes in edit user for public/ private profile

---

src/commonComponents/SchemaCard.tsx
src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/Resources/Schema/ViewSchema.tsx

- Make Schema card consistent across all interfaces.
- Added responsiveness to the Schema cards.
- Make cred-def and schema card consistent on view schema page.

Schema Card consistency across all pages

---

src/components/organization/EditOrgdetailsModal.tsx

- Text color of Private and Public button on Edit organization popup fixed

Dark and light mode fixes 

---

src/components/Issuance/CredDefSelection.tsx
src/components/Verification/Verification.tsx

- Fixed Attribute List in dark mode
- Fixed Back button in dark mode

fix:Dark mode fixes

---

src/components/Authentication/SignUpUserName.tsx

refactor: removed skip option while registration

---

src/components/Ecosystem/Dashboard.tsx

- Resolved the issue of ecosystem data handling

fix: ecosystem response handling

---

src/components/EcosystemInvite/EcoInvitationList.tsx
src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx

- Replaced ecosystem email by name
- Added repressiveness and card

Invitation issues

---

src/config/ecosystem.ts

- Resolved the issue of local storage

Fix: localstorage issue after build

---

src/api/ecosystem.ts
src/components/Ecosystem/Dashboard.tsx
src/components/Ecosystem/MemberList.tsx
src/components/EcosystemInvite/SentInvitations.tsx
src/config/apiRoutes.ts

- Member list added on dashboard.
- Implemented pagination for member list
- Implemented colour code based on status and role 
- To show the members joined an ecosystem
- To show fixed number of members on single page
- To easily distinguish between users
- Created the user friendly UI to show member list 
- Implemented the back-end API to get the members details

Feat ecosystem memberlist table

---

src/api/ecosystem.ts
src/common/enums.ts
src/commonComponents/StatusTabletTag.tsx
src/components/Ecosystem/Dashboard.tsx
src/components/Ecosystem/Endorsement/EndorsementPopup.tsx
src/components/Ecosystem/Endorsement/index.tsx
src/components/Ecosystem/MemberList.tsx
src/components/Ecosystem/interfaces/index.ts
src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx
src/components/organization/Dashboard.tsx
src/config/apiRoutes.ts
src/config/ecosystem.ts
tailwind.config.cjs

Implemented below APIs
- Submit transaction
- Reject transaction

feat: endorsement request submit and reject

---

src/components/Ecosystem/MemberList.tsx
src/components/EcosystemInvite/SentInvitations.tsx
src/components/organization/invitations/SendInvitationModal.tsx

- Handled dark mode on member list 
- Handled dark mode on send invitation model
- Handled dark mode on sent invitation model

Fix dark mode responsiveness

---

src/components/Ecosystem/Dashboard.tsx
src/components/EditEcosystemOrgModal/index.tsx

- Fixed issue of ecosystem dropdown

fix:ecosystem dashboard dropdown

---

src/components/organization/OrgDropDown.tsx

- Resolved the issue of ecosystem dashboard data mismatch
- Ecosystem dashboard data mismatching with selected org
- Cleared local storage of ecosystem id and role to update it with selected org

Fix: ecosystem dashboard data mismatch issue

---

src/api/invitations.ts
src/components/Ecosystem/MemberList.tsx
src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx
src/components/EcosystemInvite/SentInvitations.tsx
src/components/Resources/Schema/SchemasList.tsx

- Handled the pagination 
- For member list
- For sent invitation 
- For received invitations
- Handle the type error
- To handle the large data page-wise
- To improve the user experience and data handling
- Created the user friendly UI to show data and apply pagination
- Implemented the back-end API to apply pagination

fix: pagination issues in invitation and member list

---

src/api/invitations.ts
src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/organization/OrgDropDown.tsx
src/components/organization/invitations/SendInvitationModal.tsx

- Resolved orgDid selection issue to accept invitations
- Implemented get Org details API and handled errors
- Enabled the "All Schemas" option on the schema list page
- Handled responsiveness for sending invitation popup

Fix: Invitation list page issues

---

src/components/User/UserDashBoard.tsx

- Fixed the issue of - "Looks like there are no activities to display at the moment." is not visible clearly and placement of sentence is not correct.

fix:Bugs and issues

---

src/components/Ecosystem/Dashboard.tsx

- Allowed ecosystem member to access dashboard details

refactor: dashboard allowed for member

---

src/components/organization/invitations/SendInvitationModal.tsx

- Handled the form reset on action

Fix: send invitation form reset

---

src/commonComponents/datatable/index.tsx
src/components/Ecosystem/Endorsement/EndorsementCard.tsx
src/components/Ecosystem/MemberList.tsx
src/components/Resources/Schema/SchemasList.tsx

- Added org did in member list table and your status
- Handle schema endorsement

refactor : memberlist and schema

---

src/components/Authentication/SignUpUserName.tsx
src/components/CreateEcosystemOrgModal/index.tsx
src/components/EditEcosystemOrgModal/index.tsx
src/components/Profile/EditUserProfile.tsx
src/components/organization/EditOrgdetailsModal.tsx

- Resolved bug regarding the length of the input field characters differ from the suggested length.
1). Create Organization
2). Create Ecosystem
3). Edit Organization
4). Edit Ecosystem
5). Sign up user name
6). Edit user profile page
- Handled formikHandlers validations
- For better user experience

fix: length of the input field characters

---

src/components/Issuance/IssuedCrdentials.tsx
src/components/Profile/EditUserProfile.tsx
src/components/Profile/UserProfile.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/organization/OrgDropDown.tsx
src/components/organization/WalletSpinup.tsx

Resolved below issues:
- https://github.com/credebl/automation-test-suite/issues/126
- https://github.com/credebl/automation-test-suite/issues/135
- https://github.com/credebl/automation-test-suite/issues/188
- https://github.com/credebl/automation-test-suite/issues/189

fix: production issues

---

src/components/Resources/Schema/Create.tsx

Added date and time option in the datatype of attributes

feat: added date and time option in datatype of attributes

---

src/api/ecosystem.ts
src/components/CreateEcosystemOrgModal/index.tsx
src/components/Ecosystem/Dashboard.tsx
src/components/Ecosystem/EcosystemList.tsx
src/components/Ecosystem/interfaces/index.ts
src/components/EditEcosystemOrgModal/index.tsx

- Implemented auto Endorsement functionality on create Ecosystem and edit Ecosystem modal

feat:Implemented auto endorsement functionality.

---

src/commonComponents/SchemaCard.tsx
src/components/BreadCrumbs/index.tsx
src/components/Ecosystem/Dashboard.tsx
src/components/Ecosystem/EcosystemList.tsx
src/components/Ecosystem/Endorsement/index.tsx
src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx
src/components/EcosystemInvite/SentInvitations.tsx
src/components/Issuance/Connections.tsx
src/components/Issuance/CredDefSelection.tsx
src/components/Issuance/Issuance.tsx
src/components/Issuance/IssuedCrdentials.tsx
src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/Resources/Schema/ViewSchema.tsx
src/components/Verification/Connections.tsx
src/components/Verification/CredDefSelection.tsx
src/components/Verification/Verification.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/organization/Dashboard.tsx
src/components/organization/OrganizationsList.tsx
src/components/organization/invitations/ReceivedInvitations.tsx
src/components/organization/users/index.tsx

- Reduced space between Breadcrumbs globally.
- Changed Schema Card font size.
- Changed the display of Yes and No in Revocable coloumn.
- Added 'You can select only credential definition at a time' under Credential Definitions in Issuance.

fix:UI fixes

---

package-lock.json
package.json
src/app/LayoutCommon.astro
src/components/HelmetHead.tsx

- Security vulnerability fixes

refactor: security vulnerability fixes

---

src/components/Ecosystem/Dashboard.tsx
src/components/Issuance/CredDefSelection.tsx
src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/ViewSchema.tsx

- Fixed Css issues on ecosystem member dashboard.
- Changed incorrect hover messages on Request Endorsement button and create schema button on view schema page.
- For the optimal user experience.
- Implemented tailwind styles

fix:Incorrect hover messages on buttons

---

package-lock.json
src/api/Auth.ts

- Set an HTTP-only cookie on the client side
- Mitigate security vulnerability

fix:Set an HTTP-only cookie on the client side

---

src/api/Auth.ts

fix: removed `document.cookie`

---

package-lock.json
src/api/Auth.ts

- Configured Session Cookie Secure Attribute 
- Configured Session Cookie HTTP Only Attribute 
- Configured Session Cookie SameSite Attribute 
- To avoid XSS attacks 
- To avoid CSRF attacks.

Security vulnerability fix frontend - Configured cookies attributes and flags 

---

src/components/Issuance/BulkIssuance.tsx
src/components/Issuance/History.tsx
src/components/Issuance/HistoryDetails.tsx

- Replaced the Retry button from primary to secondary
- Handled pagination
- Handled alert messages based on response
- Handled dark mode 
- Created the user-friendly UI
- Implemented the back-end API to handle pagination

refactor: bulk issuance 

---

src/components/Issuance/BulkIssuance.tsx

- Worked on schema and Credential-definition drop down.
- Displayed Schema name, Credential definition and Attributes at the bottom of schema credential drop down

refactor: Schema and Credential drop down

---

package-lock.json
src/app/LayoutSidebar.astro
src/common/global.css
src/components/Issuance/BulkIssuance.tsx

Updated socket and alert messages.

feat: socket message changes in bulk issuance

---

src/commonComponents/EcosystemProfileCard.tsx
src/components/Ecosystem/Dashboard.tsx
src/components/Ecosystem/Endorsement/EndorsementCard.tsx
src/components/Ecosystem/Endorsement/index.tsx
src/components/EmptyListComponent/index.tsx
src/components/User/UserDashBoard.tsx

- Handled forbidden resource issues for 
- User dashboard
- Ecosystem dashboard
- Resolved issue when there are 3 attributes still showing dots (...) indicating more attributes.

fix: forbidden resource error

---

src/components/UserCertificate.astro

- Changes in meta title and description in certificate template

refactor: meta title and description in Certificate template

---

src/api/BulkIssuance.ts
src/common/enums.ts
src/components/Issuance/BulkIssuance.tsx
src/components/Issuance/History.tsx
src/components/Issuance/HistoryDetails.tsx
src/components/Issuance/IssuancePopup.tsx

- Implemented Socket for Retry API
- Implemented react toaster to show the alert
- Handled all status from the enum 
- Replaced SVG's from confirmation popup 
- Handled success and error message 
- Disabled the View button based on status
- Handled Status and Color codes on the history page
- Added a refresh button on the history page
- Created the user-friendly UI
- Implemented the back-end API to get status 
- Implemented socket and toaster

Fix bulk issuance changes

---

src/components/Issuance/History.tsx

refactor: messages issuance

---

src/api/BulkIssuance.ts
src/components/Issuance/BulkIssuance.tsx
src/components/Issuance/HistoryDetails.tsx

- Handled type errors
- Updated the replace text

fix: issuance minor changes

---

src/utils/TextTransform.ts

- Handled user roles in display user profile.

refactor: Roles in display user profile

---

src/commonComponents/PublicNavbar.tsx
src/components/organization/PublicOrganizationDetails.tsx
src/components/organization/interfaces/index.ts
src/components/publicProfile/OrgWalletDetails.tsx
src/components/publicProfile/OrganisationPublicProfile.tsx
src/components/publicProfile/ProfilesDesign.tsx
src/components/publicProfile/PublicProfiles.tsx
tailwind.config.cjs

- Updated explore organization page
- Added copy function for did

refactor: explore organization page

---

src/api/Agent.ts
src/components/Resources/Schema/ViewSchema.tsx
src/config/apiRoutes.ts

Refactored check on ledger button functionality:
- Integrated API to get network platform URL
- Redirect user to fetched URL

refactor: check on ledger button functionality

---

src/app/LayoutCommon.astro
src/commonComponents/CopyDid.tsx
src/components/Ecosystem/MemberList.tsx
src/components/organization/OrganizationDetails.tsx
src/components/publicProfile/OrgWalletDetails.tsx

- Refactored copy `orgDID` functionality and UI
- Added courier and inter font

refactor: copy orgdid functionality and ui, added courier and inter font

---

src/api/Auth.ts
src/commonComponents/DeviceDetailsCard.tsx
src/components/Authentication/SignInUserPasskey.tsx
src/components/Profile/AddPasskey.tsx

- Resolved passkey related bug.

fix: Passkey bug

---

src/components/Authentication/SignUpUserName.tsx
src/components/CreateEcosystemOrgModal/index.tsx
src/components/EditEcosystemOrgModal/index.tsx
src/components/Profile/EditUserProfile.tsx
src/components/organization/EditOrgdetailsModal.tsx

- Implemented appropriate validations for the following input boxes:
1). Create Organization
2). Create Ecosystem
3). Edit Organization
4). Edit Ecosystem
5). Edit User Profile 
6). Sign up user firstname and lastname input boxes
- To enhance data integrity and user experience by ensuring that the input data meets specified criteria and prevents potential errors or inconsistencies.
- Reviewed and applied relevant validation checks to each input box, including but not limited to:
1). Length constraints
2). Data type checks
3). Required field validation
Additionally, ensured that appropriate error messages are displayed to users in case of invalid input.

fix: Applied Validations for Input Boxes

---

src/api/invitations.ts
src/components/CreateEcosystemOrgModal/index.tsx
src/components/Ecosystem/Endorsement/EndorsementCard.tsx
src/components/Ecosystem/MemberList.tsx
src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx

- Refactored accept/ reject ecosystem invitation API payload.
- Refactored create ecosystem API payload.
- Refactored ecosystem member list display details.

refactor:  ecosystem organization mapping changes

---

src/api/Auth.ts

Fixed user profile details not stored in `localStorage`

fix: user profile details not storing in localstorage

---

src/commonComponents/DeviceDetailsCard.tsx

- Resolved passkey edit button alignment issue.

fix: passkey edit button alignment issue

---

src/components/Resources/Schema/Create.tsx

- Handled the border for create schema page

fix: schema border 

---

src/components/EcosystemInvite/EcoInvitationList.tsx
src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx

- Displayed the ledger network details in the ecosystem join invitation

fix: Network display for ecosystem invitations

---

src/components/Verification/CredDefSelection.tsx

- Changes in column name in cred-def selection table

changes in column name in credef selection table

---

src/api/Schema.ts
src/components/organization/OrganizationDetails.tsx
src/config/CommonConstant.ts

- Refactor all schema payload for ledger id
- To display all the schemas with ledger id

fix: All schema by ledger

---

src/components/Issuance/EmailIssuance.tsx

- Handled data type in attributes

fix: oob email issuance

---

src/components/organization/OrganizationsList.tsx

Resolved organization list pagination alignment issue

fix: organization list pagination alignment issue

---

src/components/Authentication/SignInUserPasskey.tsx
src/components/ConnectionsList/index.tsx
src/components/Issuance/ConnectionList.tsx
src/components/Issuance/IssueDashboard.tsx
src/components/Issuance/IssuedCrdentials.tsx
src/components/Issuance/interface.ts
src/components/Verification/ConnectionList.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/Verification/interface.ts
tailwind.config.cjs

- Implemented try and catch 
- Handled errors in catch
- Implemented 'trim()' and 'toLowerCase' to email
- Increased limit to 10 for pagination of connection issuance and verification
- Applied dynamic height to issue dashboard

refactor: error handling in issuance and verification

---

src/components/ConnectionsList/index.tsx
src/components/Verification/VerificationCredentialList.tsx

feat: added refresh button

---

src/components/organization/invitations/SendInvitationModal.tsx

- Fixed error while sending an invitation to join the organization

fix: send invitations

---

src/components/Resources/Schema/Create.tsx

- Fixed create schema page break
- Fixed routing issue
- Fixed alert message according to success and error
- Handled popup close timing

fix: create schema

---

src/commonComponents/ConfirmationModal.tsx
src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/SchemasList.tsx

- Handled button state on create schema 
- Handled pagination on the schema list
- Handled loading condition
- Handled empty message display

fix: schema errors

---

src/api/connection.ts
src/api/issuance.ts
src/components/Issuance/IssuedCrdentials.tsx
src/components/RoleViewButton/index.tsx
src/utils/enums/features.ts

Refactored issued credential list API integration
**NOTE:** This PR is depends on https://github.com/credebl/platform/pull/380

refactor: issued credential list 

---

src/components/organization/users/EditUserRolesModal.tsx

fix: user org role

---

src/components/Ecosystem/EcosystemList.tsx
src/components/EcosystemInvite/EcoInvitationList.tsx

- Resolved page break issue of invitation page
- Implemented Empty page for ecosystem when there is no any org created

fix: invitations and ecosystem page issue

---

src/components/EcosystemInvite/EcoInvitationList.tsx
src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx
src/components/User/UserDashBoard.tsx

Resolved ecosystem invitation details on received invitation page

fix: ecosystem invitation details

---

src/components/Verification/ProofRequestPopup.tsx

- Verification popup alignment issue resolved

fix: verification popup alignment

---

src/components/Issuance/IssuedCrdentials.tsx

- Removed "ACTION" column from issued credentials card.

fix: Changes in issued credentials card

---

src/commonComponents/PasseyAddDevicePopup.tsx

- Removed the update user details message from passkey popup

fix: passkey popup

---

src/components/Resources/Schema/Create.tsx

- Handled popup close and navigation to schema

fix: schema popup and navigation

---

src/components/Issuance/ConnectionList.tsx
src/components/Verification/ConnectionList.tsx
src/components/organization/Dashboard.tsx
tailwind.config.cjs

- Handled the alignment for organization description 
- Handled on hover border effect in connection list

fix: org description alignment 

---

src/components/User/UserDashBoard.tsx

- Fixed responsiveness for galaxy fold

fix: dashboard issues

---

src/api/ecosystem.ts
src/commonComponents/datatable/SortDataTable.tsx
src/commonComponents/datatable/interface.ts
src/components/Ecosystem/MemberList.tsx

- Implemented pagination with new data table

feat: ecosystem member pagination

---

src/commonComponents/PasseyAddDevicePopup.tsx
src/components/Profile/AddPasskey.tsx

- Handled password validation from passkey

fix: passkey validation

---

src/api/BulkIssuance.ts
src/commonComponents/datatable/SortDataTable.tsx
src/components/ConnectionsList/index.tsx
src/components/Issuance/ConnectionList.tsx
src/components/Issuance/History.tsx
src/components/Issuance/HistoryDetails.tsx
src/components/Issuance/IssuedCrdentials.tsx
src/components/Verification/ConnectionList.tsx
src/components/Verification/VerificationCredentialList.tsx

Refactor below tables
- History OOB
- History Details OOB
- Connections ( Issuance )
- Connections ( Verification )
- Updated interface for a new table

refactor: table component

---

src/components/Ecosystem/Endorsement/index.tsx
src/components/Issuance/ConnectionList.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/User/UserDashBoard.tsx
src/components/Verification/ConnectionList.tsx

- Typo fix as Prisma needs params in lowercase  
- Prisma needs params in lowercase

fix: typo fix as prisma needs params in lowercase for connection record

---

src/components/Verification/ProofRequestPopup.tsx
src/components/Verification/VerificationCredentialList.tsx

- Handled loading state for verification popup
- Implemented custom spinner and handled state

fix: verification popup data loading

---

src/commonComponents/formikerror/index.tsx
src/components/Ecosystem/interfaces/index.ts
src/components/EditEcosystemOrgModal/index.tsx
src/components/User/UserDashBoard.tsx
src/components/organization/Dashboard.tsx
src/components/organization/EditOrgdetailsModal.tsx
src/components/organization/interfaces/index.ts
src/utils/enums/processImage.ts
src/utils/processImage.ts

- Validation message while updating organization details
- Validation message while updating ecosystem details
- Handled error and success messages

fix: validation messages while updating the organization and ecosystem details

---

src/config/apiRoutes.ts

Updated submit endorsement API endpoint

refactor: submit endorsement endpoint

---

src/commonComponents/EditPopup.tsx

- Fixed error message display after closing and opening popup

fix: reset error message

---

src/commonComponents/StatusTabletTag.tsx
src/components/Ecosystem/Endorsement/EndorsementPopup.tsx

- Changes in button text and endorsement statuses.

refactor: endorsement button text and statuses

---

src/commonComponents/EcosystemProfileCard.tsx
src/commonComponents/PasseyAddDevicePopup.tsx
src/components/Authentication/KeyCloakResetPassword.tsx
src/components/Authentication/SignInUserPassword.tsx
src/components/Resources/Schema/Create.tsx
src/services/axiosIntercepter.ts

- Navigated the user to the login page once the password reset successfully
- Handled role wise data in ecosystem dropdown
- For optimal user exprience

fix: reset password

---

src/components/Resources/Schema/ViewSchema.tsx

- Handled function on basis of dropdown to display schema 
- Implemented pagination

fix: schema drop-down changes 

---

src/api/Auth.ts
src/components/Authentication/ResetPassword.tsx
src/components/Authentication/SignInUserPassword.tsx
src/components/Setting/index.tsx
src/config/apiRoutes.ts

- Implemented forgot password functionality 
- To allow user to reset password

feat: forgot password using key-cloak

---

src/api/Auth.ts
src/common/global.css
src/components/Authentication/ResetPassword.tsx
src/components/Authentication/SignInUserPassword.tsx
src/components/Issuance/EmailIssuance.tsx
src/config/apiRoutes.ts

- Merge develop branch to qa
- To update new features and stable develop version on qa environment.

merge: develop to QA

---

src/components/Ecosystem/Dashboard.tsx

fix: alignment issue

---

src/components/Verification/Verification.tsx
src/components/organization/OrgDropDown.tsx

- Handled length of org to handle scroll bar
- Handled state of verification loader to handle clicks

fix: org length in drop down and verification loader

---

src/commonComponents/PasseyAddDevicePopup.tsx
src/services/axiosIntercepter.ts
src/utils/check-session.ts

- Handled user session
- Handled passkey error
- Removed initial validations
- To handle user authentication

fix: user session management

---

src/commonComponents/PasseyAddDevicePopup.tsx

fix: passkey alignment

---

src/components/Issuance/History.tsx

- Handled pagination issue on history page

fix: pagination on history page

---

src/commonComponents/PasseyAddDevicePopup.tsx
src/components/Issuance/History.tsx

- Handled interface 
- Improved rendering conditions
- Handled sonar lint issues

fix: minor bugs fixes and performance optimisation

---

src/components/Authentication/SignInUserPassword.tsx

fix: minor fixes

---

src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/interfaces/index.ts

- Implemented the logic of the required field in schema creation
- Handled errors based on required property
- Added validation based on the required field
- To decide your required attributes based on requirements
- To give users a seamless and user-friendly experience

feat: Implementation of required attributes in schema

---

src/common/global.css
src/commonComponents/CopyDid.tsx
src/commonComponents/CredentialDefinitionCard.tsx
src/commonComponents/SchemaCard.tsx
src/commonComponents/SummaryCard.tsx
src/components/Issuance/CredDefSelection.tsx
src/components/Issuance/Issuance.tsx
src/components/Resources/Schema/ViewSchema.tsx
src/components/RoleViewButton/index.tsx
src/components/Verification/CredDefSelection.tsx
src/components/Verification/SchemaCredDefDetails.tsx
src/components/Verification/Verification.tsx

- Implemented copy functionality for IDs for the below pages:
- Issuance
- Verification
- View Schema
- Verify popup
- Disabled role-wise buttons when the user does not have access to use it
To improve user experience

feat: copy functionality for ids and disabled rolewise button if no access

---

src/components/Issuance/Issuance.tsx

fix: implementation of required attributes in issuance

---

src/components/Issuance/Issuance.tsx
src/components/organization/WalletSpinup.tsx

- Added extra checks to handle undefined values

fix: issuance page break

---

src/components/User/UserDashBoard.tsx

- Handled user access according to role

fix: role wise access for admin

---

src/commonComponents/datatable/interface.ts
src/components/Issuance/Issuance.tsx
src/components/Verification/Verification.tsx
src/components/Verification/interface.ts

- Added support for predicates
- Handled predicates validation
- To support  'Zero Knowledge Proof '

feat: predicate based proof request

---

src/components/Verification/Verification.tsx
src/config/ecosystem.ts

- Handled endorsement error
- Handled verification  validation

fix: endorsement error

---

src/components/Verification/Verification.tsx

- Added dark mode on the verification page

fix: dark mode

---

src/components/User/UserDashBoard.tsx

- Handled ecosystem invitation from the dashboard

fix: ecosystem invite from dashboard

---

src/components/User/UserDashBoard.tsx

fix: dark mode issue

---

src/components/Ecosystem/Dashboard.tsx
src/components/Ecosystem/Endorsement/EndorsementPopup.tsx
src/components/EcosystemInvite/SentInvitations.tsx
src/components/User/UserDashBoard.tsx
src/components/organization/OrganizationsList.tsx
src/components/organization/invitations/SendInvitationModal.tsx
src/components/organization/users/EditUserRolesModal.tsx
src/config/ecosystem.ts
src/pages/organizations/users.astro

- Handled user access to endorsement flow
- Handled user access to ecosystem invitation
- Handled user access to ecosystem delete invitation
- Handled user access to edit the ecosystem
- Handled button disabled on state and role
- Handled user access to ecosystem invitations from the dashboard
- Written a common function for getting organization admin and owner roles
- To optimize user experience

fix: user roles access to endorsement, ecosystem invitation

---

src/components/Issuance/EmailIssuance.tsx

- Handled the response of the email bulk issuance

fix: email bulk issuance

---

src/api/organization.ts
src/components/Setting/index.tsx
src/components/Setting/setting.ts

- Excluded delete functionality for client secret
- Implemented regenerate functionality for client secret
- Handled changed path of API route to get user roles
- To give users a seamless and user-friendly experience

refactor: client credentials flow

---

src/app/constants.ts

- Changes in env.config for white labelling changes

fix: .env variable fixes

---

src/api/Auth.ts
src/services/axiosIntercepter.ts

- Handled the error validations in `encrypt` and `decrypt` of data
- Fixed login error validation message.

fix: Error validation while encrypt & decrypt data

---

src/components/Authentication/SignInUserPasskey.tsx

fix: passkey login issue

---

src/api/ecosystem.ts
src/commonComponents/EcosystemProfileCard.tsx
src/components/Ecosystem/Dashboard.tsx
src/components/Ecosystem/EcosystemList.tsx
src/components/Ecosystem/Endorsement/EndorsementPopup.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/SearchInput/index.tsx
src/components/User/UserDashBoard.tsx
src/config/ecosystem.ts

- Implemented ecosystem search functionality
- Refactored schema search functionality

fix: bug fixes

---

src/components/organization/OrganizationDetails.tsx
src/components/organization/WalletSpinup.tsx
src/components/organization/walletCommonComponents/LegderLessMethods.tsx
src/components/organization/walletCommonComponents/SetDomainValueInput.tsx
src/components/organization/walletCommonComponents/SetPrivateKeyValue.tsx

- Implemented DID Document UI to display DID Document for web DID method
- To showcase the DID document on the user interface, enabling users to easily host

feat: implementation of DID document for did web method

---

src/api/Auth.ts
src/components/Authentication/SignInUser.tsx
src/config/ecosystem.ts

- Resolved Malformed UTF-8 data error
- Intermittent Unauthorized error  
- Implemented `try/catch` to handle exceptions
- Removed all `localStorage` while login
- Handled `JSON.parse` and `JSON.stringify`

fix: Malformed UTF-8 data error

---

package-lock.json
package.json

Upgrade crypto-js package to `4.2.0`

fix: upgrade crypto-js package

---

src/config/ecosystem.ts

fix: ecosystem role issue

---

src/components/organization/WalletSpinup.tsx

- Applied private key validations on input field

fix: private key validations

---

src/app/SideBar.astro
src/modules/UserSettings.astro
src/pages/settings.astro

- Removed unused page
- Added anti-csrf token

fix: unused page, anti-csrf token

---

.gitignore
src/components/BreadCrumbs/index.tsx
src/components/CreateEcosystemOrgModal/index.tsx
src/components/Issuance/CredDefSelection.tsx
src/components/Resources/Schema/Schemas.tsx
src/components/Resources/Schema/ViewSchema.tsx
src/components/User/UserDashBoard.tsx
src/pages/organizations/schemas/view-schema.astro
src/pages/organizations/schemas/view-schema/[schemaId].astro

- Resolved security vulnerability of hidden file expose.
- Resolved view-schema SQL dependency
- Logo not loading
- Dashboard redirection with selected organization

fix: view-schema SQL dependency, logo not loading, dashboard redirection

---

src/api/issuance.ts
src/components/Authentication/Svg.tsx
src/components/Ecosystem/Dashboard.tsx

- Modified query parameter name

fix: API query parameter and dark mode issues

---

src/middleware.ts

Resolved the issue of redirection through middleware.

fix: redirection issue

---

src/components/organization/EditOrgdetailsModal.tsx

Merging hotfixes to dev-zap-testing branch (alias main) for Security testing on DEV

hotfix: update organization payload

---

Dockerfile

refactor: dockerfile changes

---

src/components/Verification/Verification.tsx

- Changes in proof request payload with connections.
- Accommodated W3C verification with connection.

refactor: proof request payload for w3c format

---

src/components/organization/EditOrgdetailsModal.tsx

- Optional logo url addition while updating org details

fix: optional logo url addition while updating org details

---

src/api/organization.ts
src/components/organization/OrganizationDetails.tsx
src/components/organization/configuration-settings/CreateDid.tsx
src/components/organization/configuration-settings/DidList.tsx
src/components/organization/interfaces/index.ts
src/components/organization/walletCommonComponents/SetPrivateKeyValue.tsx
src/config/apiRoutes.ts
src/pages/organizations/dashboard/index.astro

- Integrated POST API for create new DID
- Integrated POST API for set primary DID
- Integrated GET API for fetch DID list
- Implemented popup modal for create new DID 
- Add option to set primary DID
- Apply network specific validations while creating new DID
- Error handling 
- The integration of POST API for creating new DID allows users to generate new decentralized identifiers within the system.
- The integration of POST API for setting a primary DID enables users to designate a specific DID as their primary one.

feat: create new did and set primary did

---

src/api/BulkIssuance.ts
src/components/Issuance/BulkIssuance.tsx
src/components/Issuance/EmailIssuance.tsx
src/config/apiRoutes.ts

- Refactored API endpoints for downloading templates, fetching credential definitions, and uploading templates
- Refactored payload for the same

refactor: modified bulk issuance payload

---

src/components/Authentication/ResetPassword.tsx
src/components/EcosystemInvite/EcoInvitationList.tsx
src/components/organization/invitations/ReceivedInvitations.tsx
src/components/publicProfile/OrgUserInfo.tsx
src/components/publicProfile/OrganisationPublicProfile.tsx
src/components/publicProfile/ProfilesDesign.tsx

- Fixed CSS issues and Avatar logo size issues.

fixed CSS and avatar issues

---

public/images/sign-warning-svgrepo-com.svg
src/common/enums.ts
src/commonComponents/PasskeyAlert.tsx
src/components/Authentication/SignInUserPasskey.tsx
src/components/Authentication/SignUpUserPasskey.tsx
src/components/Profile/AddPasskey.tsx

- Added passkey warning messages for unsupported devices.

feat: add passkey warning message for unsupported devices

---

src/api/ecosystem.ts
src/components/Resources/Schema/Create.tsx

- Modified request schema endorsement payload

refactor: request schema payload

---

src/components/Authentication/SignUpUser.tsx

- Encrypted client id and client secret for send verification mail functionality

fix:client id and secret encryption

---

src/api/Schema.ts
src/common/enums.ts
src/commonComponents/ConfirmationModal.tsx
src/commonComponents/SchemaCard.tsx
src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/Resources/Schema/interfaces/index.ts
src/components/organization/DeleteOrganization.tsx

-Refactored existing flow of schema creation to support W3C schema type along with existing types.
- Implemented CSS changes in schema list for W3C schema.
- Changes in get all schemas from platform functionality.

feat: create schema flow for w3c

---

src/api/verification.ts
src/common/enums.ts
src/commonComponents/SchemaCard.tsx
src/commonComponents/interface.ts
src/components/Issuance/EmailIssuance.tsx
src/components/Issuance/Issuance.tsx
src/components/Issuance/IssuedCrdentials.tsx
src/components/Resources/Schema/Create.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/Resources/Schema/interfaces/index.ts
src/components/Verification/SchemaCredDefDetails.tsx
src/components/Verification/SchemaSelection.tsx
src/components/Verification/Verification.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/Verification/VerificationDashboard.tsx
src/components/Verification/interface.ts
src/config/CommonConstant.ts

- Refactor existing flow of verification with connections.
- Add payload structure which will be work for both INDY and W3C schemaTypes.

feat: W3C verifcation with connections.

---

src/components/Resources/Schema/SchemasList.tsx
src/components/organization/walletCommonComponents/DedicatedAgent.tsx
src/components/organization/walletCommonComponents/SharedAgent.tsx

- Fixed Bug: Wallet successfully created without selecting "Method and Network" after changing ledger.
- Done changes to show W3C schema in all schema dropdown.

fix: create wallet UI for shared and dedicated agents.

---

src/components/Ecosystem/Endorsement/index.tsx
src/components/Issuance/BulkIssuance.tsx
src/components/Issuance/EmailIssuance.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/User/UserDashBoard.tsx
src/components/Verification/VerificationSchemasList.tsx
src/components/organization/walletCommonComponents/DedicatedAgent.tsx
src/components/organization/walletCommonComponents/SharedAgent.tsx
src/config/CommonConstant.ts

- Fixed issue: Radio button state was not cleared while creating shared and dedicated wallet.

fix: radio button state issue on shared and dedicated wallet creation UI.

---

.github/workflows/deploy.yml

fix: replaced deploy.yml file

---

src/components/organization/walletCommonComponents/DedicatedAgent.tsx
src/components/organization/walletCommonComponents/SharedAgent.tsx

- Refactored network name while fetching ledgerConfig details

hotfix: replace network name

---

src/components/Issuance/BulkIssuance.tsx
src/components/Issuance/EmailIssuance.tsx
src/components/Issuance/Issuance.tsx
src/components/organization/walletCommonComponents/DedicatedAgent.tsx

- Fixed issue: Unable to store credentials during connection issuance when using schemas from other organizations.
- Dedicated agent UI dark mode fixes.
- Fixed issue: Unable to view schemas for OOB email and bulk issuance for INDY.

fix: Unable to store credentials during connection issuance when using schemas from other organizations.

---

.github/workflows/deploy-qa.yml
.github/workflows/deploy.yml

feat: changes in workflow file

---

.github/workflows/deploy.yml

fix: changes in deploy yml file

---

src/components/User/UserDashBoard.tsx

- Fixed: React Minified issue.

fix: user-dashboard Minified React issue

---

src/components/User/UserDashBoard.tsx

- Sync changes on DCO fixes branch

fix: sync changes on DCO fixes branch

---

src/components/Resources/Schema/SchemasList.tsx
src/components/organization/Dashboard.tsx

- Fix: Resolved React Minified error on schema list and organization dashboard.

fix: react minified error

---

src/components/CreateOrgModal/index.tsx
src/components/organization/EditOrgdetailsModal.tsx

- Fixed character length of organization.

fix: org character limit

---

src/components/User/UserDashBoard.tsx

- Fixed issue of schema details on user dashboard
issue link: https://github.com/credebl/automation-test-suite/issues/476

fix: schema details issue on user dashboard

---

src/pages/organizations/verification/verify-credentials/schemas/cred-defs/connections/index.astro
src/pages/organizations/verification/verify-credentials/schemas/cred-defs/index.astro

- Fix: page not found issue in create connection proof request flow .

fix: page not found issue in create connection proof request flow 

---

.github/ISSUE_TEMPLATE/DMP_2024.yml
LICENSE
README.md
package.json
src/pages/index.astro
src/pages/privacy-policy.md
src/pages/terms-of-use.md

- Update occurrences of `Blockster Labs` to `Ayanworks`

chore: transition from Blockster Labs to Ayanworks

---

.env.demo
src/components/CreateOrgModal/index.tsx
src/components/organization/EditOrgdetailsModal.tsx

feat: added .env.demo file

---

src/components/Authentication/SignInUserPasskey.tsx

- removed login API call for passkey

feat: removed login API call for passkey

---

src/components/Authentication/SignInUserPasskey.tsx

- removed login API call from passkey based signin

refactor: removed login API call from passkey based signin

---

src/common/enums.ts
src/commonComponents/SchemaCard.tsx

- Added conditions for Polygon Mainnet.

refactor: Schema card changes for Polygon ledger.

---

src/common/enums.ts
src/commonComponents/SchemaCard.tsx

- refactor: Schema card changes for polygon mainnet.
- feat: Created enum for network values.

refactor: Schema card changes for Polygon ledger. (#804)

---

src/components/Issuance/BulkIssuance.tsx
src/components/Issuance/EmailIssuance.tsx
src/components/organization/walletCommonComponents/DedicatedAgent.tsx

- fixed: https://github.com/credebl/automation-test-suite/issues/480 
- fixed: https://github.com/credebl/automation-test-suite/issues/465

fix: UI missalignment on dedicated agent config form.

---

src/components/User/UserDashBoard.tsx

Fix for orgDid missing value

---

src/components/Profile/DisplayProfileImg.tsx
src/components/Profile/DisplayUser.tsx

- Handled conditions for undefined value for user roles

fix: handled conditions for undefined value for user roles

---

.github/workflows/deploy-dev.yml

- Added variable in dev.yml file

feat: added frontend url variable in yml file

---

src/components/Authentication/SignUpUser.tsx

-  Check user exist API response changes.

fix: Check user exist API response changes.

---

.github/workflows/deploy.yml

fix: deploy.yml file

---

src/commonComponents/CustomCheckbox.tsx

- Fixes for verification flow checkbox issue

fix: changes for verification flow checkbox changes

---

src/pages/index.astro

- Updated links of documentation and social media

hotfix: updated links

---

.github/workflows/deploy-qa.yml

feat: updated qa yml file

---

.github/workflows/deploy-qa.yml

- fix: changes in deploy-qa.yml file

fix: changes in deploy-qa.yml file

---

.github/workflows/deploy-dev.yml

###What?
- Updated deploy.yml file

refactor: yml file of studio

---

src/config/pathRoutes.ts
src/pages/organizations/schemas/[schemaId].astro
src/pages/organizations/schemas/view-schema/[schemaId].astro

- Resolved following bug:
https://credebl.atlassian.net/browse/CREDEBL-436

fix: schema route changes

---

src/components/organization/OrganizationsList.tsx

Organization not found error message was displaying instead of notification of organization not available.

fix: CREDEBL-441: Organization not found message display issue fixed.

---

.github/workflows/deploy-qa.yml
src/commonComponents/datatable/SortDataTable.tsx
src/commonComponents/datatable/interface.ts
src/components/ConnectionsList/index.tsx
src/components/Issuance/ConnectionList.tsx
src/components/Issuance/IssuedCrdentials.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/Verification/ConnectionList.tsx
src/components/Verification/VerificationCredentialList.tsx
src/components/organization/OrganizationsList.tsx
src/components/organization/invitations/Invitations.tsx
src/components/organization/users/Members.tsx
src/pages/index.astro

Sync changes from DEV to QA

---

src/components/Authentication/FooterBar.tsx
src/components/CopyrightNotice.astro
src/pages/index.astro

Update copyright in footer in aligned with LFDT migration

docs: update copyright information in footer

---

.github/workflows/deploy.yml

- Corrected deno project name in deploy.yml file.

refactor: yml file

---

src/common/enums.ts
src/commonComponents/CustomSelect.tsx
src/commonComponents/SchemaCard.tsx
src/components/Issuance/BulkIssuance.tsx
src/components/Issuance/EmailIssuance.tsx
src/components/Resources/Schema/SchemasList.tsx
src/components/Verification/EmailAttributesSelection.tsx
src/components/Verification/EmailCredDefSelection.tsx
src/components/Verification/VerificationSchemasList.tsx
src/components/organization/invitations/SendInvitationModal.tsx
src/config/CommonConstant.ts
tailwind.config.cjs

- Resolved below issues:
1). Predicates validations not working properly
2). Search functionality is not working properly
3). Double attributes are selected in verification flow
4). While sending org-invitation, it don't support `global` domain
5). Handled conditions for array datatype schemas

fix: resolved ui issues

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-qa.yml
src/components/User/UserDashBoard.tsx
src/components/Verification/Connections.tsx
src/components/Verification/EmailVerification.tsx

- Schema route changes from dashboard
- Handled conditions for undefined values

fix: schema route changes from dashboard

---

nextjs/src/app/api/connection.ts
nextjs/src/app/connections/page.tsx
nextjs/src/app/dashboard/page.tsx
nextjs/src/components/DateTooltip.tsx
nextjs/src/components/EmptyMessage.tsx
nextjs/src/components/layout/header.tsx
nextjs/src/components/layout/user-nav.tsx
nextjs/src/components/org-switcher.tsx
nextjs/src/components/theme-selector.tsx
nextjs/src/components/ui/dropdown-menu.tsx
nextjs/src/components/ui/table.tsx
nextjs/src/config/CommonConstant.ts
nextjs/src/features/connections/components/Connections.tsx
nextjs/src/features/connections/types/connections-interface.ts
nextjs/src/features/dashboard/components/SchemasList.tsx
nextjs/src/features/dashboard/components/dashboard.tsx
nextjs/src/utils/DateConversion.ts

- Completed Connection component with full UI and API integration.
Display data in a table format with searching, pagination, and sorting functionality.
- Added a Create Wallet banner on the dashboard.
Banner is shown when no wallet is created, with a Create Wallet button.
- Repositioned theme.
- Removed the "Select Organization" text.

complete connection component and create wallet banner

---

src/common/enums.ts
src/commonComponents/CustomSelect.tsx
src/commonComponents/SchemaCard.tsx

- Handled conditions on bulk issuance, email issuance and schema list screen for nested schemas.

chore: handled conditions for nested schemas

---

nextjs/src/app/globals.css
nextjs/src/app/theme.css
nextjs/src/features/auth/components/EmailVerificationForm.tsx
nextjs/src/features/auth/components/SignUpUser.tsx
nextjs/src/features/auth/components/SignUpViewPage.tsx
nextjs/src/features/auth/components/VerifyEmail.tsx
nextjs/src/features/organization/components/CreateOrganizationModal.tsx
nextjs/src/features/organization/components/OrganizationDashboard.tsx
nextjs/src/features/organization/components/OrganizationList.tsx

- Resolved issue of email pre-population on Sign-up page after email verification
- Custom CSS Changes & Loader implementation for specific components
- Theme related CSS changes

Fix: email prepopulate issue on sign up page

---

.env.demo

- update public-base-url in .env.demo

chore: update public-base-url in .env.demo

---

nextjs/src/features/organization/components/CreateOrganizationModal.tsx
nextjs/src/features/organization/components/OrganizationList.tsx
nextjs/src/features/organization/components/interfaces/organization.ts
nextjs/src/features/wallet/DedicatedAgentForm.tsx
nextjs/src/features/wallet/LedgerConfig.tsx
nextjs/src/features/wallet/SetPrivateKeyValue.tsx
nextjs/src/features/wallet/SharedAgentForm.tsx
nextjs/src/features/wallet/WalletSpinupComponent.tsx

- Refactored Create organization floe along with wallet setup flow.

fix: create org flow with agent setup

---

nextjs/src/features/organization/components/CreateOrganizationModal.tsx
nextjs/src/features/organization/components/OrganizationDashboard.tsx
nextjs/src/features/organization/components/interfaces/organization.ts

- Resolved: Bug(CREDEBL UI ): Country, State, and City not displayed in dropdown on the "Create Organization".
- Resolved: Bug(CREDEBL UI ): Schemas and Credentials count displayed on organization dashboard without wallet creation.
- Resolved: Bug(CREDEBL): Organization ID is missing" error message displayed on UI while creating wallet.

fix: issues on org dashboard and wallet creation

---

nextjs/src/features/organization/components/OrganizationDashboard.tsx

- Added dynamic data in schema, credential and users card on organization dashboard

resolved issue on org dashboard

---

nextjs/src/features/organization/connectionIssuance/components/IssueDashboard.tsx
nextjs/src/features/organization/connectionIssuance/components/connectionsTables/SortDataTable.tsx
nextjs/src/features/organization/connectionIssuance/type/ConnectionIssueTable.ts
nextjs/src/features/organization/connectionIssuance/type/Connections.ts
nextjs/src/features/organization/connectionIssuance/type/CredDefSelection.ts
nextjs/src/features/organization/connectionIssuance/type/Credentials.ts
nextjs/src/features/organization/connectionIssuance/type/Dashboard.ts
nextjs/src/features/organization/connectionIssuance/type/Issuance.ts
nextjs/src/features/organization/connectionIssuance/type/SchemaCard.ts
nextjs/src/features/organization/connectionIssuance/type/SchemasList.ts

- Added Issuance Dashboard page.
-  Types for all the feature components for connection issuance.

Refactor/Issuance Dashboard page and types

---

nextjs/src/app/organizations/credentials/issue/schemas/page.tsx
nextjs/src/features/organization/connectionIssuance/components/ConnectionIssueTable.tsx
nextjs/src/features/organization/connectionIssuance/components/ConnectionList.tsx
nextjs/src/features/organization/connectionIssuance/components/Issuance.tsx
nextjs/src/features/organization/connectionIssuance/components/connectionsTables/SortDataTable.tsx

- After latest pull fixed the issue "Connection list not getting fetched"
-  Caused due to changes done to the api response return data .

fix: Resolved issues related to type and eslint

---

nextjs/src/features/organization/components/CreateOrganizationModal.tsx
nextjs/src/features/organization/components/OrganizationDashboard.tsx
nextjs/src/features/organization/components/OrganizationDetails.tsx
nextjs/src/features/organization/components/OrganizationList.tsx
nextjs/src/features/wallet/CreateDidComponent.tsx
nextjs/src/features/wallet/DedicatedAgentLedgerConfig.tsx
nextjs/src/features/wallet/DidListComponent.tsx
nextjs/src/features/wallet/LedgerConfig.tsx
nextjs/src/features/wallet/WalletSpinupComponent.tsx

Fixed below bugs:
- "No organizations found." message is misaligned and appears in the left corner instead of center of the screen
- Seed displayed twice on ledger configuration screen
- Remove text ‘scan to connection’ from QR code component
- Inconsistent success and error messages on create did component
- New created DID is not visible until user refreshes the page
- Delete button should be in red color
- Error message is displayed on edit organization page when clicked on back button for country, state and city fields.

fix: UI issues from organiation dashboard, wallet spinup and organization list components

---

nextjs/src/components/CredentialDefinitionCard.tsx

- Fixed the problem for issue button not working in credential definition page

Fixed path related issue on credential defination page for issuance
