- package.json
- src/commonComponents/QRcode.tsx
- tsconfig.json
- Resolved connection with holder issue.
> Fixed connection with holder issue

- src/components/organization/Dashboard.tsx
- Disabled view schema button if the wallet not exists
> fix:disable schema access

- src/commonComponents/ProofRequestPopup.tsx
- src/components/Verification/VerificationCredentialList.tsx
- Added loader for verify button
- Changed popup message for verification
> fix:verification popup loader

- src/commonComponents/datatable/index.tsx
- src/components/Issuance/Issuance.tsx
WHAT:
- In this pull request, I've made changes in issuance.
- Changed issuance attribute name to display name.
- I've made changes in credential definition select button colour code.
WHY:
- The reason for these changes is for user experience on issuance page display name should be visible. 
- As per design requirements.
> Fix: Issuance attribute name credential definition select button changes

- src/commonComponents/SchemaCard.tsx
- src/components/Profile/EditUserProfile.tsx
- src/components/Resources/Schema/SchemasList.tsx
- src/components/organization/EditOrgdetailsModal.tsx
- src/pages/index.astro
Reset position of explore organisations on navbar as per new landing page design.
Changed edit user close svg from back arrow to close.
Bug: Close button redirects to users page instead of closing notification #134
Bug: Missing space between text and plus (+) icon on the schemas and create organization Page #131
Bug: Updated profile name not displayed on the profile's slider #124
Bug: The length of the description characters differ from the suggested length #138
Resolved type errors faced while working.
Removed commented and unused code.
> fix: explore org button position and bug fixes

- src/commonComponents/DeviceDetailsCard.tsx
- src/components/Profile/EditUserProfile.tsx
- src/components/organization/invitations/Invitations.tsx
- Fixed invitations icon in dark mode
- Added space between colon(:) and date displayed
- Modified the passkey icon in both modes
- Fixed 'No File Chosen' in dark mode
> fix: dark mode alignment fixes

- src/api/invitations.ts
- src/common/enums.ts
- src/components/Authentication/SignInUser.tsx
- src/components/CreateEcosystemOrgModal/index.tsx
- src/components/Ecosystem/Dashboard.tsx
- src/components/Ecosystem/Endorsement/EndorsementCard.tsx
- src/components/Ecosystem/Endorsement/index.tsx
- src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx
- src/components/EcosystemInvite/SentInvitations.tsx
- src/components/Resources/Schema/SchemasList.tsx
- src/components/User/UserDashBoard.tsx
- src/config/CommonConstant.ts
- src/config/ecosystem.ts
- Updated create and accept ecosystem APIs
- Added condition in get ecosystem and dashboard API
- Roles API response handled in `checkEcosystem` function
> Refactor: accept and create ecosystem api and stored ecosystem role in config

- src/api/ecosystem.ts
- src/common/enums.ts
- src/commonComponents/StatusTabletTag.tsx
- src/components/Ecosystem/Endorsement/EndorsementCard.tsx
- src/components/Ecosystem/Endorsement/EndorsementPopup.tsx
- src/components/Ecosystem/Endorsement/index.tsx
- src/components/EditEcosystemOrgModal/index.tsx
- Integration of sign endorsement API.
> feat:sign endorsement

- src/commonComponents/EcosystemProfileCard.tsx
Resolved the issue of the ecosystem selection option
> fix: ecosystem selection option

- src/components/EcosystemInvite/EcoSystemReceivedInvitations.tsx
- Resolved issue: Reject button enabled without selecting organization from select organization dropdown.
> fix: Reject button issue on ecosystem invitations page

- src/components/Ecosystem/EcosystemList.tsx
- src/components/Ecosystem/MemberList.tsx
- src/components/Issuance/History.tsx
- src/components/Issuance/HistoryDetails.tsx
- src/components/Issuance/IssuedCrdentials.tsx
- src/components/Verification/VerificationCredentialList.tsx
- src/components/organization/OrganizationsList.tsx
- src/components/organization/invitations/Invitations.tsx
- src/components/organization/invitations/ReceivedInvitations.tsx
- src/components/organization/users/Members.tsx
- src/components/publicProfile/OrganisationPublicProfile.tsx
- Enhanced search capabilities
- Incorporated debouncing mechanism
- To address undesired API calls
> refactor: search capabilities

- src/common/enums.ts
- src/components/Issuance/IssuedCrdentials.tsx
- Enhanced the status indicators by incorporating additional color codes
- Added a refresh button 
- To understand the status of credentials
- To avoid hard refresh
- Implemented user-friendly UI with color codes
> refactor: credentials status and refresh button

- src/components/Authentication/SignInUserPasskey.tsx
- src/components/Authentication/SignInUserPassword.tsx
- src/components/Resources/Schema/Create.tsx
Resolved the issue of duplicate attribute name entry while creating schema
https://github.com/credebl/automation-test-suite/issues/127
> fix: duplicate attribute name in create schema

- src/api/connection.ts
- src/api/issuance.ts
- src/api/verification.ts
- src/components/ConnectionsList/index.tsx
- src/components/Issuance/ConnectionList.tsx
- src/components/Issuance/IssuedCrdentials.tsx
- src/components/Verification/ConnectionList.tsx
- src/components/Verification/VerificationCredentialList.tsx
- src/components/Verification/interface.ts
- Integrate pagination and searching feature functionality at the time of fetching connections list 
- Integrate pagination and searching feature functionality at the time of fetching issued credentials list 
- Integrate pagination and searching feature functionality at the time of fetching proof presentations list
> feat: Integrate pagination and searching functionality

- src/commonComponents/PasseyAddDevicePopup.tsx
- src/components/Authentication/SignUpUserName.tsx
- src/components/CreateEcosystemOrgModal/index.tsx
- src/components/organization/EditOrgdetailsModal.tsx
- Resolved to create  and edit Ecosystem and Org popup alignment issue
- Dark mode issue of "view button' of creat passkey
- Resolved the text "Create Password" and the "Back arrow" position
> fix: create ecosystem org alignment and passkey dark mode issues

- src/components/Verification/ProofRequestPopup.tsx
- src/components/Verification/VerificationCredentialList.tsx
- src/components/Verification/interface.ts
- Resolved the issue "View" button, displayed the previous data for a few seconds sometimes and then displayed actual data on the verified details popup
> fix: verified details popup data display

- src/components/Profile/AddPasskey.tsx
- src/components/Profile/DisplayUserProfile.tsx
- src/components/Profile/EditUserProfile.tsx
- Fixes extra space between two words for small screen
- Override the default behavior
> fix: extra space between words

- src/common/global.css
- src/components/Ecosystem/Endorsement/EndorsementPopup.tsx
- src/config/ecosystem.ts
- Handled UI and functionality for ecosystem if a user is not an `Admin` or `Owner` but is `Ecosystem Lead` then all the ecosystem features are read-only.
- If a user is `Admin` or `Owner` and is `Ecosystem Lead` then only he/she will be able to perform ecosystem-related operations.
> fix: ecosystem forbidden resource error

- src/components/Issuance/EmailIssuance.tsx
- src/components/Issuance/Issuance.tsx
- Handled the position of error message in issuance 
- To optimize user exprience
> fix: error message position

- src/api/Agent.ts
- src/api/Auth.ts
- src/app/LayoutCommon.astro
- src/common/enums.ts
- src/commonComponents/CopyDid.tsx
- src/components/Authentication/SignInUserPasskey.tsx
- src/components/Authentication/SignInUserPassword.tsx
- src/components/organization/Dashboard.tsx
- src/components/organization/OrganizationDetails.tsx
- src/components/organization/WalletSpinup.tsx
- src/components/organization/interfaces/index.ts
- src/components/organization/walletCommonComponents/GenerateBtnPolygon.tsx
- src/components/organization/walletCommonComponents/LegderLessMethods.tsx
- src/components/organization/walletCommonComponents/SetDomainValueInput.tsx
- src/components/organization/walletCommonComponents/SetPrivateKeyValue.tsx
- src/components/organization/walletCommonComponents/TokenWarningMessage.tsx
- src/config/CommonConstant.ts
- src/config/apiRoutes.ts
- src/pages/api/auth/signin.ts
- src/pages/api/auth/signout.ts
- src/services/axiosIntercepter.ts
- src/utils/check-session.ts
- Implemented refresh token functionality
- Implemented multiple `DID` methods while creating wallet
- Integrated `polygon` ledger 
- To get the updated `access_token` from `refresh_token` if current is expired.
-  A single endpoint ensures the generality of `DID` creation.
> develop to qa

- src/components/Authentication/SignInUserPasskey.tsx
- src/components/Authentication/SignInUserPassword.tsx
- src/components/Profile/UserProfile.tsx
- Reduced user-profile payload to store in the `localStorage`
- Stored only below fields
- id
- profileImg
- firstName
- email
- enableEcosystem
- multiEcosystemSupport
> fix: user-profile payload

- src/api/verification.ts
- Change variable for pagination in getting all verification list DTO from 'searchByText' to 'search'
- To maintain consistency for pagination
> fix: pagination parameter name to sync with backend

- src/components/organization/EditOrgdetailsModal.tsx
Invalid data uri when updating org info without updating image.
Issue arises only when updating details of an org(except image) that already has an image.
> fix: invalid data uri while updating org details

- src/commonComponents/EcosystemProfileCard.tsx
- src/components/EcosystemInvite/EcoInvitationList.tsx
- src/components/organization/invitations/ReceivedInvitations.tsx
- Applied custom CSS for custom avatar components.
> fix: custom-avatar-css-issues

- src/components/Issuance/IssuedCrdentials.tsx
- In the issuance flow, org did was not found in some cases due to issue in optional chaining.
> fix:org did not found issue resolved in issuance flow

- src/app/LayoutCommon.astro
##WHAT
Removed duplicate Google API CDN.
> HotFix: Security error in console while downloading QR code in wallet details

- src/commonComponents/CustomCheckbox.tsx
- src/commonComponents/SchemaCard.tsx
- src/commonComponents/interface.ts
- src/components/Resources/Schema/ViewSchema.tsx
- src/components/Verification/VerificationSchemasList.tsx
- src/components/Verification/interface.ts
- fix: Double attributes displayed for a single schema during OOB and connection verification.
- fix: Schema Details Not Visible on "Schemas" Page When Creating Credential Definition.
> fix: Double attributes displayed for a single schema during OOB and connection verification.

- src/components/Issuance/Issuance.tsx
- Changed DID from schema to org DID
> hotfix:issuer DID in w3c issuance
